# Generated by Django 2.0.8 on 2022-01-19 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ext_id", models.TextField(unique=True)),
                ("link", models.URLField(help_text="Profile link on the channel.")),
                ("title", models.TextField(help_text="Title of the post.")),
                ("message", models.TextField(help_text="The description or caption.")),
                ("user_tags", models.TextField(help_text="User tags in an image.")),
                (
                    "views",
                    models.IntegerField(
                        default=0, help_text="Number of views on the post."
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        default=0, help_text="Number of likes on the post."
                    ),
                ),
                (
                    "shares",
                    models.IntegerField(
                        default=0, help_text="Number of shares on the post."
                    ),
                ),
                (
                    "comments",
                    models.IntegerField(
                        default=0, help_text="Number of comments on the post."
                    ),
                ),
                ("thumbnail", models.TextField(help_text="URI to an image.")),
                (
                    "publish_time",
                    models.DateTimeField(help_text="time published on channel in UTC"),
                ),
                (
                    "request_time",
                    models.DateTimeField(
                        help_text="Time requested by our collector in UTC."
                    ),
                ),
                ("media_type", models.TextField(help_text="Image, video, etc...")),
                (
                    "channel",
                    models.CharField(
                        help_text="YouTube, Facebook, etc.", max_length=30
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the channel.", max_length=200),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="YouTube, Facebook, etc.", max_length=30
                    ),
                ),
                (
                    "ext_id",
                    models.TextField(
                        help_text="Profile id on the channel.", unique=True
                    ),
                ),
                ("link", models.URLField(help_text="Profile link on the channel.")),
                (
                    "followers",
                    models.IntegerField(
                        default=0, help_text="Most recent follower count."
                    ),
                ),
                ("thumbnail", models.TextField(help_text="URI to a profile image")),
                (
                    "is_business",
                    models.NullBooleanField(help_text="IG business account if True."),
                ),
                (
                    "is_public",
                    models.NullBooleanField(help_text="Public profile if True."),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                help_text="Profile id on the channel.",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Profile",
                to_field="ext_id",
            ),
        ),
    ]
